### ISSUE TITLE
Compile stopped working

### ISSUE THREAD

**Issue by metaladdict** [jdiehl/brackets-less-autocompile#107]
Hello,

I had a strange issue. From one day to the other, the compiler stopped working.
After a few hours, I got it to work with 2 dirty edit:
1) /main.js, in the documentSaved event, "EditorManager.getCurrentFullEditor().document !== document" always returned false - So I removed this condition
2) /node/LessCompiler.js - it didn't find less-plugin-clean-css so I changed it to
var LessPluginCleanCSS = require('@wikimedia/less-plugin-clean-css');
I tried to install it globally but it didn't work

I don't know what happened, I haven't done windows or brackets updates
I tried older versions of brackets and your plugin, nothing worked until I did these changes after tracking the bug.

**Comment by jdiehl** [comment]
Hi @metaladdict and sorry about the inconvenience. I fixed the bug that caused this. Please update the extension to 1.1.14 and you should be all set.

**Comment by sleepymonday** [comment]
The same issue happened after updating. The less compiler just stopped working showing the error `"Error in file 'undefined' on line undefined: Operation on an invalid type"`. Still can't make it work.

**Comment by jdiehl** [comment]
Just tested it again with a clean install of the latest Brackets version (1.14.2-17770) and the latest version of the extension (1.1.14) on my Mac and it works. Please try reinstalling Brackets and the extension.

**Comment by sleepymonday** [comment]
> Just tested it again with a clean install of the latest Brackets version (1.14.2-17770) and the latest version of the extension (1.1.14) on my Mac and it works. Please try reinstalling Brackets and the extension.

Just tried again with a clean install and realized that what's not working is actually the `main` feature. 
Using `compress and out` works, but when using `main` (most of my less files does) the above error appears.

**Comment by sleepymonday** [comment]
Ok. I realize what the problem was. Just posting it in case anyone has the same issue. I had a mixin function using complex calc forms like this:
**My mixin:**
```
.calc(@measure: left, @math: ~"100% - 10px") {
  @{measure}: -webkit-calc(@math);
  @{measure}: -moz-calc(@math);
  @{measure}: calc(@math);
}
```
**Example usage**
`.calc(@measure: height, @math: ~"100%" - @thumbH);`

This used to be compiled but for some reason it doesn't now. So just changing those functions solved my issue.
